apiVersion: machineconfiguration.openshift.io/v1
kind: MachineConfigPool
metadata:
  name: "worker-cyclic"
spec:
  machineConfigSelector:
    matchExpressions:
      - {key: machineconfiguration.openshift.io/role, operator: In, values: [worker,worker-cyclic]}
  nodeSelector:
    matchLabels:
      node-role.kubernetes.io/worker-cyclic: ""
