apiVersion: ripsaw.cloudbulldozer.io/v1alpha1
kind: Benchmark
metadata:
  name: cyclictest-${UUID}
  namespace: benchmark-operator
spec:
  elasticsearch:
    server: $_es
  workload:
    name: "cyclictest"
    args:
      node_selector: node-role.kubernetes.io/worker-rt=
      duration: ${DURATION}
      disable_cpu_balance: ${DISABLE_CPU_BALANCE}
      stressng: ${STRESSNG}
      pod:
        requests:
          memory: ${MEMORY_REQUESTS}
          cpu: ${CPU_REQUESTS}
        limits:
          memory: ${MEMORY_LIMITS}
          cpu: ${CPU_LIMITS}
