---
kind: BuildConfig
apiVersion: build.openshift.io/v1
metadata:
  name: {{.JobName}}-{{.Replica}}
spec:
  triggers:
  - type: GitHub
    github:
      secret: {{.JobName}}-{{.Replica}}
  - type: ImageChange
  - type: ConfigChange
  source:
    git:
      uri: {{.gitUri}}
    type: Git
  strategy:
    type: Source
    sourceStrategy:
{{ if index . "sourceStratEnv" }}
      env:
        - name: {{.sourceStratEnv}}
{{ end }}
      from:
        kind: ImageStreamTag
        name: {{.fromSource}}:{{.fromSourceVersion}}
        namespace: 'openshift'
{{ if index . "postCommitScript" }}
  postCommit:
    script: {{.postCommitScript}}
{{ end }}
  output:
    to:
      kind: ImageStreamTag
      name: {{.imageStream}}-{{.Replica}}:latest
  affinity:
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
        - matchExpressions:
          - key: node-role.kubernetes.io/worker
            operator: Exists
        - matchExpressions:
          - key: node-role.kubernetes.io/infra
            operator: DoesNotExist
        - matchExpressions:
          - key: node-role.kubernetes.io/master
            operator: DoesNotExist
        - matchExpressions:
          - key: node-role.kubernetes.io/workload
            operator: DoesNotExist
