kind: Deployment
apiVersion: apps/v1
metadata:
  name: webserver-{{.Replica}}-{{.Iteration}}
spec:
  template:
    metadata:
      labels:
        name: webserver-{{.Replica}}-{{.Iteration}}
    spec:
      containers:
      - name: webserver
        image: quay.io/cloud-bulldozer/sampleapp:latest
        resources:
          requests:
            memory: "10Mi"
            cpu: "10m"
        ports:
        - containerPort: 8080
          protocol: TCP
        imagePullPolicy: IfNotPresent
        securityContext:
          privileged: false
      restartPolicy: Always
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: node-role.kubernetes.io/worker
                operator: Exists
            - matchExpressions:
              - key: node-role.kubernetes.io/infra
                operator: DoesNotExist
            - matchExpressions:
              - key: node-role.kubernetes.io/master
                operator: DoesNotExist
            - matchExpressions:
              - key: node-role.kubernetes.io/workload
                operator: DoesNotExist
  replicas: 1
  selector:
    matchLabels:
      name: webserver-{{.Replica}}-{{.Iteration}}
  triggers:
  - type: ConfigChange
  strategy:
    type: RollingUpdate
