apiVersion: ripsaw.cloudbulldozer.io/v1alpha1
kind: Benchmark
metadata:
  name: scale
  namespace: benchmark-operator
spec:
  uuid: ${UUID}
  elasticsearch:
    url: ${ES_SERVER}
  clustername: ${CLOUD_NAME}
  metadata:
    collection: ${METADATA_COLLECTION}
    privileged: true
    targeted: false
    serviceaccount: backpack-view
  test_user: ${CLOUD_NAME}-scale
  workload:
    name: scale_openshift
    args:
      label:
        key: node-role.kubernetes.io/${WORKLOAD_NODE_ROLE}
        value: ""
      tolerations:
        key: role
        value: workload
        effect: NoSchedule
      scale: ${size}
      serviceaccount: scaler
      poll_interval: ${POLL_INTERVAL}
      post_sleep: ${POST_SLEEP}
