apiVersion: ripsaw.cloudbulldozer.io/v1alpha1
kind: Benchmark
metadata:
  name: scale
  namespace: benchmark-operator
spec:
  uuid: ${UUID}
  elasticsearch:
    url: ${ES_SERVER}
  clustername: ${CLOUD_NAME}
  metadata:
    collection: ${METADATA_COLLECTION}
    privileged: true
    targeted: false
    serviceaccount: backpack-view
  test_user: ${CLOUD_NAME}-scale
  workload:
    name: scale_openshift
    args:
      scale: ${size}
      serviceaccount: scaler
      poll_interval: ${POLL_INTERVAL}
      post_sleep: ${POST_SLEEP}
      rosa:
        cluster_name: ${ROSA_CLUSTER_NAME}
        env: ${ROSA_ENVIRONMENT}
        token: ${ROSA_TOKEN}
      aws:
        access_key_id: ${AWS_ACCESS_KEY_ID}
        secret_access_key: ${AWS_SECRET_ACCESS_KEY}
        default_region: ${AWS_DEFAULT_REGION}
