apiVersion: v1
kind: Pod
metadata:
  name: mb-pod
  namespace: default
spec:
  containers:
    - name: mb-container
      image: "quay.io/mukrishn/snomb:2"
      command: [ "/bin/sh", "-c", "mb -i /etc/config/requests.json -d 86400" ] # -d in seconds
      volumeMounts:
      - name: config-volume
        mountPath: /etc/config
  resources:
      limits:
        memory: '16Gi'
        cpu: 16
      requests:
        memory: '16Gi'
        cpu: 16
  volumes:
    - name: config-volume
      configMap:
        name: request-configmap
  restartPolicy: Never