---

apiVersion: machineconfiguration.openshift.io/v1
kind: MachineConfigPool
metadata:
  name: ${CUSTOM_NAME}
spec:
  machineConfigSelector:
    matchExpressions:
      - {key: machineconfiguration.openshift.io/role, operator: In, values: [worker, "${CUSTOM_VALUE}"]}
  nodeSelector:
    matchLabels:
      node-role.kubernetes.io/custom: ${CUSTOM_LABEL}