#export OPENSHIFT_BASE_DOMAIN= #required field
export OPENSHIFT_INSTALL_APIVERSION=v1
export OPENSHIFT_INSTALL_SSH_PUB_KEY_FILE=/root/.ssh/id_rsa.pub
export GOPATH=/root/.go
#export OPENSHIFT_CLUSTER_NAME= #required field
export OPENSHIFT_MASTER_COUNT=3
export OPENSHIFT_WORKER_COUNT=3
export OPENSHIFT_MASTER_INSTANCE_TYPE=n1-standard-8
export OPENSHIFT_WORKER_INSTANCE_TYPE=n1-standard-4
export OPENSHIFT_MASTER_ROOT_VOLUME_SIZE=120
export OPENSHIFT_MASTER_ROOT_VOLUME_TYPE=io1
export OPENSHIFT_MASTER_ROOT_VOLUME_IOPS=3000
export OPENSHIFT_WORKER_ROOT_VOLUME_SIZE=100
export OPENSHIFT_WORKER_ROOT_VOLUME_TYPE=gp2
export OPENSHIFT_WORKER_ROOT_VOLUME_IOPS=0
export OPENSHIFT_CIDR=10.128.0.0/10
export OPENSHIFT_MACHINE_CIDR=10.0.0.0/16
export OPENSHIFT_SERVICE_NETWORK=172.30.0.0/16
export OPENSHIFT_HOST_PREFIX=23
export OPENSHIFT_NETWORK_TYPE=OpenShiftSDN
export OPENSHIFT_POST_INSTALL_POLL_ATTEMPTS=600
export OPENSHIFT_TOGGLE_INFRA_NODE=true
export OPENSHIFT_TOGGLE_WORKLOAD_NODE=true
export MACHINESET_METADATA_LABEL_PREFIX=machine.openshift.io
export OPENSHIFT_INFRA_NODE_INSTANCE_TYPE=n1-standard-4
export OPENSHIFT_WORKLOAD_NODE_INSTANCE_TYPE=n1-standard-4
export OPENSHIFT_INFRA_NODE_VOLUME_SIZE=100
export OPENSHIFT_INFRA_NODE_VOLUME_TYPE=pd-ssd
export OPENSHIFT_INFRA_NODE_VOLUME_IOPS=0
export OPENSHIFT_WORKLOAD_NODE_VOLUME_SIZE=120
export OPENSHIFT_WORKLOAD_NODE_VOLUME_TYPE=pd-ssd
export OPENSHIFT_WORKLOAD_NODE_VOLUME_IOPS=0
export OPENSHIFT_PROMETHEUS_RETENTION_PERIOD=15d
export OPENSHIFT_PROMETHEUS_STORAGE_CLASS=standard
export OPENSHIFT_PROMETHEUS_STORAGE_SIZE=5Gi
export OPENSHIFT_ALERTMANAGER_STORAGE_CLASS=standard
export OPENSHIFT_ALERTMANAGER_STORAGE_SIZE=1Gi



# gcp specific
#export GCP_REGION= #required field
#export GCP_PROJECT= #required field
#export GCP_SERVICE_ACCOUNT= #required field
#export GCP_SERVICE_ACCOUNT_EMAIL= #required field
#export GCP_AUTH_KEY_FILE= #required field
export GOOGLE_CREDENTIALS=${GCP_AUTH_KEY_FILE}