---

apiVersion: ripsaw.cloudbulldozer.io/v1alpha1
kind: Benchmark
metadata:
  name: uperf-${CR_NAME}-${WORKLOAD}-network-${pairs}
  namespace: benchmark-operator
spec:
  uuid: ${UUID}
  elasticsearch:
    url: ${ES_SERVER}
  metadata:
    collection: ${METADATA_COLLECTION}
    serviceaccount: backpack-view
    privileged: true
    targeted: ${METADATA_TARGETED}
  cerberus_url: "$CERBERUS_URL"
  workload:
    name: uperf
    args:
      run_id: "$RUN_ID"
      hostnetwork: ${HOSTNETWORK}
      serviceip: ${SERVICEIP}
      networkpolicy: ${NETWORK_POLICY}
      pin: true
      pin_server: "$server"
      pin_client: "$client"
      multus:
        enabled: false
      samples: 3
      pair: ${pairs}
      nthrs:
        - 1
      protos:
        - tcp
        - udp
      test_types:
        - stream
        - rr
      sizes:
        - 64
      runtime: ${UPERF_RUNTIME}
