kind: Pod
apiVersion: v1
metadata:
  name: prometheus-sizing-{{.Replica}}
  labels:
    name: prometheus-sizing
spec:
  nodeSelector:
    node-role.kubernetes.io/worker: ""
  containers:
  - name: prometheus-sizing
    image: {{.containerImage}}
    ports:
    - containerPort: 8080
      protocol: TCP
    imagePullPolicy: IfNotPresent
    securityContext:
      privileged: false
      allowPrivilegeEscalation: false
      capabilities:
        drop:
          - ALL
      runAsNonRoot: true
      runAsUser: 1001
      seccompProfile:
        type: RuntimeDefault