kind: Pod
apiVersion: v1
metadata:
  name: prometheus-sizing-{{.Replica}}
  labels:
    name: prometheus-sizing
spec:
  nodeSelector:
    node-role.kubernetes.io/worker: ""
  containers:
  - name: prometheus-sizing
    image: {{.containerImage}}
    ports:
    - containerPort: 8080
      protocol: TCP
    imagePullPolicy: IfNotPresent
    securityContext:
      privileged: false
