# vi: expandtab shiftwidth=2 softtabstop=2

# First scenario warm ups ingress controller caches, assigns the router pods to the infra nodes and increase the number of nb threads
- termination: http
  connections: 200
  samples: 1
  duration: 1m
  path: /1024.html
  concurrency: 18
  tool: wrk
  serverReplicas: 45
  requestTimeout: 10s
  tuningPatch: '{"spec":{"tuningOptions":{"threadCount": 64}, "nodePlacement": {"nodeSelector": {"matchLabels": {"node-role.kubernetes.io/infra": ""}}}, "replicas": 2}}'
  delay: 10s
  warmup: true

- termination: http
  connections: 200
  samples: 2
  duration: 3m
  path: /1024.html
  concurrency: 18
  tool: wrk
  serverReplicas: 45
  requestTimeout: 10s
  delay: 10s

- termination: edge
  connections: 200
  samples: 2
  duration: 3m
  path: /1024.html
  concurrency: 18
  tool: wrk
  serverReplicas: 45
  requestTimeout: 10s
  delay: 10s

- termination: reencrypt
  connections: 200
  samples: 2
  duration: 3m
  path: /1024.html
  concurrency: 18
  tool: wrk
  serverReplicas: 45
  requestTimeout: 10s
  delay: 10s

- termination: passthrough
  connections: 200
  samples: 2
  duration: 3m
  path: /1024.html
  concurrency: 18
  tool: wrk
  serverReplicas: 45
  requestTimeout: 10s
  delay: 10s

- termination: reencrypt
  connections: 200
  samples: 2
  duration: 3m
  path: /1024.html
  concurrency: 5
  tool: hloader
  serverReplicas: 45
  requestTimeout: 10s
  tuningPatch: '{"metadata":{"annotations": {"ingress.operator.openshift.io/default-enable-http2": "true"}}}'
  http2: true

- termination: passthrough
  connections: 200
  samples: 2
  duration: 3m
  path: /1024.html
  concurrency: 5
  tool: hloader
  serverReplicas: 45
  requestTimeout: 10s
  http2: true

