apiVersion: v1
kind: Service
metadata:
  labels:
    app: http-perf
  name: http-perf-{{.Replica}}
spec:
  ports:
  - name: http
    port: 8080
    protocol: TCP
    targetPort: 8080
  - name: https
    port: 8443
    protocol: TCP
    targetPort: 8443
  selector:
    app: nginx-{{.Replica}}
  type: ClusterIP
