apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: http-perf
  name: http-perf-{{.Replica}}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx-{{.Replica}}
  template:
    metadata:
      labels:
        app: nginx-{{.Replica}}
    spec:
      containers:
      - image: quay.io/openshift-scale/nginx:latest
        name: nginx
        resources:
          requests:
            memory: "10Mi"
            cpu: "10m"    
      dnsPolicy: ClusterFirst
      restartPolicy: Always
