kind: Pod
apiVersion: v1
metadata:
  name: {{.JobName}}-{{.Iteration}}
  labels:
    name: {{.JobName}}
spec:
  containers:
  - name: node-density
    image: {{.containerImage}}
    resources:
      requests:
        memory: "10Mi"
        cpu: "10m"
    ports:
    - containerPort: 8080
      protocol: TCP
    imagePullPolicy: IfNotPresent
    securityContext:
      privileged: false
    affinity:
      nodeAffinity:
        requiredDuringSchedulingIgnoredDuringExecution:
          nodeSelectorTerms:
          - matchExpressions:
            - key: node-role.kubernetes.io/worker
              operator: Exists
          - matchExpressions:
            - key: node-role.kubernetes.io/infra
              operator: DoesNotExist
          - matchExpressions:
            - key: node-role.kubernetes.io/master
              operator: DoesNotExist
          - matchExpressions:
            - key: node-role.kubernetes.io/workload
              operator: DoesNotExist
