apiVersion: apps/v1
kind: Deployment
metadata:
  name: contacts
spec:
  template:
    spec:
      containers:
      - name: contacts
        env:
        - name: ENABLE_TRACING
          value: "false"
