apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: ledger-db
spec:
  template:
    spec:
      nodeSelector:
        node-role.kubernetes.io/worker: ""
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
            - weight: 100
              podAffinityTerm:
                labelSelector:
                  matchLabels:
                    app: ledger-db
                topologyKey: "kubernetes.io/hostname"
      topologySpreadConstraints:
        - maxSkew: 1
          topologyKey: "kubernetes.io/hostname"
          whenUnsatisfiable: ScheduleAnyway
          labelSelector:
            matchLabels:
              app: ledger-db
      securityContext:
        runAsUser: 0
        runAsGroup: 0
        fsGroup: 0
      containers:
      - name: postgres
        image: us-central1-docker.pkg.dev/bank-of-anthos-ci/bank-of-anthos/ledger-db:v0.6.6@sha256:db8bb60717be587cb3c419a73012cebc7c8cf464a77ae45fd78502f0fa3922d8
        envFrom:
        - configMapRef:
            name: environment-config
        - configMapRef:
            name: ledger-db-config
        - configMapRef:
            name: demo-data-config
        securityContext:
          runAsUser: 0
          privileged: true
        ports:
        - containerPort: 5432
        volumeMounts:
        - mountPath: /var/lib/postgresql/data
          name: postgresdb
  volumeClaimTemplates:
  - metadata:
      name: postgresdb
    spec:
      accessModes: [ReadWriteOnce]
      resources:
        requests:
          storage: 1Gi

