apiVersion: apps/v1
kind: Deployment
metadata:
  name: transactionhistory
spec:
  replicas: 2
  template:
    spec:
      nodeSelector:
        node-role.kubernetes.io/worker: ""
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
            - weight: 100
              podAffinityTerm:
                labelSelector:
                  matchLabels:
                    app: transactionhistory
                topologyKey: "kubernetes.io/hostname"
      topologySpreadConstraints:
        - maxSkew: 1
          topologyKey: "kubernetes.io/hostname"
          whenUnsatisfiable: ScheduleAnyway
          labelSelector:
            matchLabels:
              app: transactionhistory
      containers:
      - name: transactionhistory
        env:
        - name: ENABLE_TRACING
          value: "false"
        - name: ENABLE_METRICS
          value: "false"

