apiVersion: apps/v1
kind: Deployment
metadata:
  name: userservice
spec:
  template:
    spec:
      containers:
      - name: userservice
        env:
        - name: ENABLE_TRACING
          value: "false"
