---
apiVersion: ripsaw.cloudbulldozer.io/v1alpha1
kind: Benchmark
metadata:
  name: uperf-${WORKLOAD}-${PAIRS}
  namespace: benchmark-operator
spec:
  uuid: ${UUID}
  clustername: ${CLUSTER_NAME}
  system_metrics:
    collection: ${SYSTEM_METRICS_COLLECTION}
    prom_url: https://prometheus-k8s.openshift-monitoring.svc.cluster.local:9091
    es_url: ${ES_SERVER}
    prom_token: ${PROM_TOKEN}
    metrics_profile: node-metrics.yml
  elasticsearch:
    url: ${ES_SERVER}
  metadata:
    collection: ${METADATA_COLLECTION}
    serviceaccount: backpack-view
    targeted: ${METADATA_TARGETED}
  workload:
    name: uperf
    args:
      run_id: "$RUN_ID"
      hostnetwork: ${HOSTNETWORK}
      serviceip: ${SERVICEIP}
      servicetype: ${SERVICETYPE}
      metallb:
        addresspool: "${ADDRESSPOOL}"
        service_etp: "${SERVICE_ETP}" 
      networkpolicy: ${NETWORK_POLICY}
      multus:
        enabled: false
      samples: ${SAMPLES}
      pair: ${PAIRS}
      nthrs:
        - 1
      protos:
        - tcp
        - udp
      test_types:
        - stream
        - rr
      sizes:
        - 64
        - 1024
        - 16384
      runtime: 60
