---
apiVersion: ripsaw.cloudbulldozer.io/v1alpha1
kind: Benchmark
metadata:
  name: uperf-${WORKLOAD}-${PAIRS}
  namespace: benchmark-operator
spec:
  uuid: ${UUID}
  elasticsearch:
    url: ${ES_SERVER}
  metadata:
    collection: ${METADATA_COLLECTION}
    serviceaccount: backpack-view
    privileged: true
    targeted: ${METADATA_TARGETED}
  cluster:
    name: ${CLUSTER_NAME}
    id: ${CLUSTER_ID}
    ocp_version: ${OPENSHIFT_VERSION}
    kubernetes_version: ${KUBERNETES_VERSION}
    platform: ${CLOUD_TYPE}
    sdn: ${CLUSTER_NETWORK_TYPE}
  workload:
    name: uperf
    args:
      run_id: "$RUN_ID"
      hostnetwork: ${HOSTNETWORK}
      serviceip: ${SERVICEIP}
      servicetype: ${SERVICETYPE}
      metallb:
        addresspool: "${ADDRESSPOOL}"
        service_etp: "${SERVICE_ETP}" 
      networkpolicy: ${NETWORK_POLICY}
      pin: true
      pin_server: "$server"
      pin_client: "$client"
      multus:
        enabled: false
      samples: ${SAMPLES}
      pair: ${PAIRS}
      nthrs:
        - 1
      protos:
        - tcp
        - udp
      test_types:
        - stream
        - rr
      sizes:
        - 64
        - 1024
        - 16384
      runtime: 60
