---
apiVersion: ripsaw.cloudbulldozer.io/v1alpha1
kind: Benchmark
metadata:
  name: uperf-${WORKLOAD}-${PAIRS}
  namespace: benchmark-operator
spec:
  uuid: ${UUID}
  clustername: ${CLUSTER_NAME}
  elasticsearch:
    url: ${ES_SERVER}
  metadata:
    collection: ${METADATA_COLLECTION}
    serviceaccount: backpack-view
    privileged: true
    targeted: ${METADATA_TARGETED}
  workload:
    name: uperf
    args:
      run_id: "$RUN_ID"
      hostnetwork: ${HOSTNETWORK}
      serviceip: ${SERVICEIP}
      networkpolicy: ${NETWORK_POLICY}
      pin: true
      pin_server: "$server"
      pin_client: "$client"
      multus:
        enabled: false
      samples: ${SAMPLES}
      pair: ${PAIRS}
      nthrs:
        - 1
      protos:
        - tcp
      test_types:
        - stream
      sizes:
        - 1024
      runtime: 10
