---

apiVersion: ripsaw.cloudbulldozer.io/v1alpha1
kind: Benchmark
metadata:
  name: uperf-benchmark-${WORKLOAD}-network-${pairs}
  namespace: benchmark-operator
spec:
  uuid: ${UUID}
  elasticsearch:
    url: ${ES_SERVER}
  clustername: ${cloud_name}
  test_user: ${cloud_name}-${WORKLOAD}-ci-${pairs}p
  metadata:
    collection: ${METADATA_COLLECTION}
    serviceaccount: backpack-view
    privileged: true
    targeted: ${METADATA_TARGETED}
  cerberus_url: "$CERBERUS_URL"
  workload:
    name: uperf
    args:
      run_id: "$RUN_ID"
      hostnetwork: ${HOSTNETWORK}
      serviceip: ${SERVICEIP}
      networkpolicy: ${NETWORK_POLICY}
      pin: true
      pin_server: "$server"
      pin_client: "$client"
      multus:
        enabled: false
      samples: 1
      pair: ${pairs}
      nthrs:
        - 1
      protos:
        - tcp
      test_types:
        - stream
      sizes:
        - 1024
      runtime: 10
