# PLEASE DON"T DELETE THIS FILE, IT'S BEING USED BY AIRFLOW FOR BASELINE CLUSTER STAT
---
global:
  indexerConfig:
    enabled: true
    esServers: ["${ES_SERVER}"]
    insecureSkipVerify: true
    defaultIndex: ${ES_INDEX}
    type: elastic