---
kind: Build
apiVersion: build.openshift.io/v1
metadata:
  name: {{.JobName}}-{{.Replica}}
spec:
  serviceAccount: builder
  source:
    dockerfile: |-
      FROM registry.fedoraproject.org/fedora-minimal:latest
      RUN touch $(date +%s)
    type: Dockerfile
  strategy:
    dockerStrategy:
      from:
        kind: DockerImage
        name: registry.fedoraproject.org/fedora-minimal:latest
    type: Source
  output:
    to:
      kind: ImageStreamTag
      name: {{.prefix}}-{{.Replica}}:latest
  affinity:
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
        - matchExpressions:
          - key: node-role.kubernetes.io/worker
            operator: Exists
        - matchExpressions:
          - key: node-role.kubernetes.io/infra
            operator: DoesNotExist
        - matchExpressions:
          - key: node-role.kubernetes.io/master
            operator: DoesNotExist
        - matchExpressions:
          - key: node-role.kubernetes.io/workload
            operator: DoesNotExist
