---
global:
  writeToFile: false
  indexerConfig:
    enabled: {{.INDEXING}}
    esServers: ["{{.ES_SERVER}}"]
    insecureSkipVerify: true
    defaultIndex: {{.ES_INDEX}}
    type: elastic
  measurements:
    - name: podLatency
      esIndex: {{.ES_INDEX}}

{{ if eq .PPROF_COLLECTION "True" }}
    - name: pprof
      pprofInterval: {{ .PPROF_COLLECTION_INTERVAL }}
      pprofDirectory: /tmp/pprof-data
      pprofTargets:
      - name: kube-apiserver-cpu
        namespace: "openshift-kube-apiserver"
        labelSelector: {app: openshift-kube-apiserver}
        bearerToken: {{ .BEARER_TOKEN }}
        url: https://localhost:6443/debug/pprof/profile?timeout=30
      - name: kube-apiserver-heap
        namespace: "openshift-kube-apiserver"
        labelSelector: {app: openshift-kube-apiserver}
        bearerToken: {{ .BEARER_TOKEN }}
        url: https://localhost:6443/debug/pprof/heap
      - name: kube-controller-manager-heap
        namespace: "openshift-kube-controller-manager"
        labelSelector: {app: kube-controller-manager}
        bearerToken: {{ .BEARER_TOKEN }}
        url: https://localhost:10257/debug/pprof/heap

      - name: kube-controller-manager-cpu
        namespace: "openshift-kube-controller-manager"
        labelSelector: {app: kube-controller-manager}
        bearerToken: {{ .BEARER_TOKEN }}
        url: https://localhost:10257/debug/pprof/profile?timeout=30

      - name: etcd-heap
        namespace: "openshift-etcd"
        labelSelector: {app: etcd}
        cert: {{ .CERTIFICATE }}
        key: {{ .PRIVATE_KEY }}
        url: https://localhost:2379/debug/pprof/heap

      - name: etcd-cpu
        namespace: "openshift-etcd"
        labelSelector: {app: etcd}
        cert: {{ .CERTIFICATE }}
        key: {{ .PRIVATE_KEY }}
        url: https://localhost:2379/debug/pprof/profile?timeout=30


{{ end }}

jobs:
  - name: cluster-density
    jobIterations: {{.JOB_ITERATIONS}}
    qps: {{.QPS}}
    burst: {{.BURST}}
    namespacedIterations: true
    namespace: cluster-density-{{.UUID}}
    podWait: {{.POD_WAIT}}
    cleanup: {{.CLEANUP}}
    waitFor: {{.WAIT_FOR}}
    waitWhenFinished: {{.WAIT_WHEN_FINISHED}}
    verifyObjects: {{.VERIFY_OBJECTS}}
    errorOnVerify: {{.ERROR_ON_VERIFY}}
    maxWaitTimeout: {{.MAX_WAIT_TIMEOUT}}
    objects:

      - objectTemplate: https://raw.githubusercontent.com/cloud-bulldozer/e2e-benchmarking/master/workloads/kube-burner/workloads/cluster-density/templates/imagestream.yml
        replicas: 3
        inputVars:
          prefix: cluster-density-src
          image: quay.io/cloud-bulldozer/ubi8-go-toolset

      - objectTemplate: https://raw.githubusercontent.com/cloud-bulldozer/e2e-benchmarking/master/workloads/kube-burner/workloads/cluster-density/templates/imagestream.yml
        replicas: 3
        inputVars:
          prefix: cluster-density-dst
          image: quay.io/cloud-bulldozer/ubi8-go-toolset

      - objectTemplate: https://raw.githubusercontent.com/cloud-bulldozer/e2e-benchmarking/master/workloads/kube-burner/workloads/cluster-density/templates/buildconfig.yml
        replicas: 3
        inputVars:
          from: cluster-density-src
          to: cluster-density-dst
          gitUri: https://github.com/cloud-bulldozer/hello-openshift.git  
          nodeSelector: "{{.POD_NODE_SELECTOR}}"

      - objectTemplate: https://raw.githubusercontent.com/cloud-bulldozer/e2e-benchmarking/master/workloads/kube-burner/workloads/cluster-density/templates/imagestream.yml
        replicas: 6
        inputVars:
          prefix: cluster-density

      - objectTemplate: https://raw.githubusercontent.com/cloud-bulldozer/e2e-benchmarking/master/workloads/kube-burner/workloads/cluster-density/templates/build.yml
        replicas: 6
        inputVars:
          prefix: cluster-density
          nodeSelector: "{{.POD_NODE_SELECTOR}}"

      - objectTemplate: https://raw.githubusercontent.com/cloud-bulldozer/e2e-benchmarking/master/workloads/kube-burner/workloads/cluster-density/templates/deployment.yml
        replicas: 1
        inputVars:
          podReplicas: 2
          name: deployment-2pod
          nodeSelector: "{{.POD_NODE_SELECTOR}}"

      - objectTemplate: https://raw.githubusercontent.com/cloud-bulldozer/e2e-benchmarking/master/workloads/kube-burner/workloads/cluster-density/templates/service.yml
        replicas: 1
        inputVars:
          name: deployment-2pod
        
      - objectTemplate: https://raw.githubusercontent.com/cloud-bulldozer/e2e-benchmarking/master/workloads/kube-burner/workloads/cluster-density/templates/deployment.yml
        replicas: 2
        inputVars:
          podReplicas: 1
          name: deployment-1pod
          nodeSelector: "{{.POD_NODE_SELECTOR}}"
      
      - objectTemplate: https://raw.githubusercontent.com/cloud-bulldozer/e2e-benchmarking/master/workloads/kube-burner/workloads/cluster-density/templates/service.yml
        replicas: 2
        inputVars:
          name: deployment-1pod

      - objectTemplate: https://raw.githubusercontent.com/cloud-bulldozer/e2e-benchmarking/master/workloads/kube-burner/workloads/cluster-density/templates/route.yml
        replicas: 1
        inputVars:
          name: deployment-2pod

      - objectTemplate: https://raw.githubusercontent.com/cloud-bulldozer/e2e-benchmarking/master/workloads/kube-burner/workloads/cluster-density/templates/route.yml
        replicas: 2
        inputVars:
          name: deployment-1pod

      - objectTemplate: https://raw.githubusercontent.com/cloud-bulldozer/e2e-benchmarking/master/workloads/kube-burner/workloads/cluster-density/templates/secret.yml
        replicas: 10

      - objectTemplate: https://raw.githubusercontent.com/cloud-bulldozer/e2e-benchmarking/master/workloads/kube-burner/workloads/cluster-density/templates/configmap.yml
        replicas: 10
