---
kind: Route
apiVersion: route.openshift.io/v1
metadata:
  name: {{.name}}-{{.Replica}}
spec:
  host: www.{{.name}}.example-{{.Iteration}}-{{.Replica}}.com
  to:
    kind: Service
    name: {{.name}}-{{.Iteration}}-{{.Replica}}
  tls:
    termination: edge
