kind: Pod
apiVersion: v1
metadata:
  name: {{.JobName}}-{{.Iteration}}
  labels:
    name: {{.JobName}}
spec:
  nodeSelector: {{.nodeSelector}}
  containers:
  - name: pod-density-heavy
    image: {{.containerImage}}
    ports:
    - containerPort: 8080
      protocol: TCP
    imagePullPolicy: IfNotPresent
    readinessProbe:
      httpGet:
        path: /
        port: 8080
      periodSeconds: {{ .readinessPeriod }}
      failureThreshold: 1
      timeoutSeconds: 60
      initialDelaySeconds: 30
    livenessProbe:
      httpGet:
        path: /
        port: 8080
      periodSeconds: {{ .livenessPeriod }}
      failureThreshold: 1
      timeoutSeconds: 15
      initialDelaySeconds: 30
    securityContext:
      privileged: false
