---
apiVersion: k8s.cni.cncf.io/v1
kind: NetworkAttachmentDefinition
metadata:
    name: bridge-whereabouts-10-1-0-0
spec:
    config: |-
        {
            "cniVersion": "0.3.1",
            "name": "bridge-whereabouts-10-1-0-0",
            "type": "bridge",
            "bridge": "cni0",
            "ipam": {
                "type": "whereabouts",
                "range": "10.1.0.0/21"
            }
        }

