apiVersion: v1
kind: Pod
metadata:
  name: nginx-{{randInteger 0 1000000}}
  labels:
    label1: foo-1
spec:
  containers:
  - name: nginx
    image: quay.io/openshift-scale/nginx:latest
    ports:
    - containerPort: 8080
