---
global:
  writeToFile: false
  indexerConfig:
    enabled: ${INDEXING}
    esServers: ["${ES_SERVER}"]
    insecureSkipVerify: true
    defaultIndex: ${ES_INDEX}
    type: elastic
  measurements:
    - name: podLatency
      esIndex: ${ES_INDEX}
{{ if eq .PPROF_COLLECTION "True" }}
    - name: pprof
      pprofInterval: {{ .PPROF_COLLECTION_INTERVAL }}
      pprofDirectory: /tmp/pprof-data
      pprofTargets:

      - name: kube-apiserver-cpu
        namespace: "openshift-kube-apiserver"
        labelSelector: {app: openshift-kube-apiserver}
        bearerToken: {{ .BEARER_TOKEN }}
        url: https://localhost:6443/debug/pprof/profile?timeout=30

      - name: kube-apiserver-heap
        namespace: "openshift-kube-apiserver"
        labelSelector: {app: openshift-kube-apiserver}
        bearerToken: {{ .BEARER_TOKEN }}
        url: https://localhost:6443/debug/pprof/heap

      - name: kube-controller-manager-heap
        namespace: "openshift-kube-controller-manager"
        labelSelector: {app: kube-controller-manager}
        bearerToken: {{ .BEARER_TOKEN }}
        url: https://localhost:10257/debug/pprof/heap

      - name: kube-controller-manager-cpu
        namespace: "openshift-kube-controller-manager"
        labelSelector: {app: kube-controller-manager}
        bearerToken: {{ .BEARER_TOKEN }}
        url: https://localhost:10257/debug/pprof/profile?timeout=30

      - name: etcd-heap
        namespace: "openshift-etcd"
        labelSelector: {app: etcd}
        cert: {{ .CERTIFICATE }}
        key: {{ .PRIVATE_KEY }}
        url: https://localhost:2379/debug/pprof/heap

      - name: etcd-cpu
        namespace: "openshift-etcd"
        labelSelector: {app: etcd}
        cert: {{ .CERTIFICATE }}
        key: {{ .PRIVATE_KEY }}
        url: https://localhost:2379/debug/pprof/profile?timeout=30
{{ end }}
jobs:
  - name: max-namespaces
    jobIterations: ${TEST_JOB_ITERATIONS}
    qps: ${QPS}
    burst: ${BURST}
    namespacedIterations: true
    namespace: max-namespaces-${UUID}
    podWait: ${POD_WAIT}
    cleanup: ${CLEANUP}
    waitFor: ${WAIT_FOR}
    waitWhenFinished: ${WAIT_WHEN_FINISHED}
    verifyObjects: ${VERIFY_OBJECTS}
    errorOnVerify: ${ERROR_ON_VERIFY}
    maxWaitTimeout: ${MAX_WAIT_TIMEOUT}
    objects:

      - objectTemplate: postgres-deployment.yml
        replicas: 1
        inputVars:
          nodeSelector: "${POD_NODE_SELECTOR}"

      - objectTemplate: app-deployment.yml
        replicas: 5
        inputVars:
          readinessPeriod: 10
          livenessPeriod: 10
          nodeSelector: "${POD_NODE_SELECTOR}"

      - objectTemplate: postgres-service.yml
        replicas: 1

      - objectTemplate: secret.yml
        replicas: 10
