---
global:
  writeToFile: false
  indexerConfig:
    enabled: {{.INDEXING}}
    esServers: ["{{.ES_SERVER}}"]
    insecureSkipVerify: true
    defaultIndex: {{.ES_INDEX}}
    type: elastic
  measurements:
    - name: podLatency
      esIndex: {{.ES_INDEX}}
jobs:
  - name: node-density-heavy
    jobIterations: {{.JOB_ITERATIONS}}
    qps: {{.QPS}}
    burst: {{.BURST}}
    namespacedIterations: false
    namespace: node-density-heavy-{{.UUID}}
    podWait: {{.POD_WAIT}}
    cleanup: {{.CLEANUP}}
    waitFor: {{.WAIT_FOR}}
    waitWhenFinished: {{.WAIT_WHEN_FINISHED}}
    verifyObjects: {{.VERIFY_OBJECTS}}
    errorOnVerify: {{.ERROR_ON_VERIFY}}
    maxWaitTimeout: {{.MAX_WAIT_TIMEOUT}}
    objects:

      - objectTemplate: https://raw.githubusercontent.com/cloud-bulldozer/e2e-benchmarking/master/workloads/kube-burner/workloads/node-density-heavy/templates/postgres-deployment.yml
        replicas: 1
        inputVars:
          nodeSelector: "{{.POD_NODE_SELECTOR}}"

      - objectTemplate: https://raw.githubusercontent.com/cloud-bulldozer/e2e-benchmarking/master/workloads/kube-burner/workloads/node-density-heavy/templates/app-deployment.yml
        replicas: 1
        inputVars:
          readinessPeriod: 10
          livenessPeriod: 10
          nodeSelector: "{{.POD_NODE_SELECTOR}}"

      - objectTemplate: https://raw.githubusercontent.com/cloud-bulldozer/e2e-benchmarking/master/workloads/kube-burner/workloads/node-density-heavy/templates/postgres-service.yml
        replicas: 1
