---
kind: Deployment
apiVersion: apps/v1
metadata:
  name: {{.name}}-{{.Iteration}}-{{.Replica}}
spec:
  selector:
    matchLabels:
      app: {{.name}}-{{.Iteration}}-{{.Replica}}
  template:
    metadata:
      labels:
        app: {{.name}}-{{.Iteration}}-{{.Replica}}
    spec:
      containers:
      - name: {{.name}}
        image: quay.io/cloud-bulldozer/hello-openshift:latest
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8080
          protocol: TCP
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: node-role.kubernetes.io/worker
                operator: Exists
            - matchExpressions:
              - key: node-role.kubernetes.io/infra
                operator: DoesNotExist
            - matchExpressions:
              - key: node-role.kubernetes.io/master
                operator: DoesNotExist
            - matchExpressions:
              - key: node-role.kubernetes.io/workload
                operator: DoesNotExist
