---

apiVersion: ripsaw.cloudbulldozer.io/v1alpha1
kind: Benchmark
metadata:
  name: kube-burner-${WORKLOAD}-${UUID}
  namespace: benchmark-operator
spec:
  uuid: ${UUID}
  # Metadata information
  elasticsearch:
    url: ${ES_SERVER}
  metadata:
    collection: ${METADATA_COLLECTION}
    privileged: true
  prometheus:
    # Prometheus bearer token
    prom_token: ${PROM_TOKEN}
    # Prometheus URL with full URL format. https://prometheus-k8s.openshift-monitoring.svc.cluster.local:9091
    prom_url: ${PROM_URL}
  workload:
    name: kube-burner
    args:
      extra_env_vars:
        PPROF_COLLECTION: ${PPROF_COLLECTION}
        PPROF_COLLECTION_INTERVAL: ${PPROF_COLLECTION_INTERVAL}
        BEARER_TOKEN: ${BEARER_TOKEN}
        PRIVATE_KEY: ${PRIVATE_KEY}
        CERTIFICATE: ${CERTIFICATE}
      # Kube-burner configmap name
      configmap: kube-burner-cfg-${UUID}
      # Kube-burner Job timeout
      job_timeout: ${JOB_TIMEOUT}
      # ES index name
      default_index: ${ES_INDEX}
      # Pin kube-burner to a node using the value of the label kubernetes.io/hostname
      pin_server: ${NODE_SELECTOR}
      # Use a custom kube-burner image
      image: ${KUBE_BURNER_IMAGE}
      # Log level. Allowed, info and debug
      log_level: ${LOG_LEVEL}
      # kube-burner pod tolerations
      tolerations: ${TOLERATIONS}
      # Prometheus step size
      step: ${STEP_SIZE}
