apiVersion: v1
kind: Pod
metadata:
  name: mb-pod
spec:
  containers:
    - name: mb-container
      image: "quay.io/mukrishn/snomb:2"
      command: [ "/bin/sh", "-c", "mb -i /etc/config/requests.json -d 48000" ]
      volumeMounts:
      - name: config-volume
        mountPath: /etc/config
  volumes:
    - name: config-volume
      configMap:
        name: request-configmap
  restartPolicy: Never