export KUBECONFIG=~/.kube/config
export ENGINE=podman
export RUNTIME=60
export TERMINATIONS="http edge passthrough reencrypt mix"
export URL_PATH="/1024.html"
export TLS_REUSE=true
export SAMPLES=2
export HOST_NETWORK=true
export NUMBER_OF_ROUTERS=2
export NODE_SELECTOR='{node-role.kubernetes.io/workload: }'
export QUIET_PERIOD=60s
export ES_SERVER=https://search-perfscale-dev-chmf5l4sh66lvxbnadi4bznl3a.us-west-2.es.amazonaws.com:443
export ES_INDEX=router-test-results
export PREFIX=$(oc get clusterversion version -o jsonpath="{.status.desired.version}")
export ES_SERVER_BASELINE=""
export SMALL_SCALE_BASELINE_UUID=""
export LARGE_SCALE_BASELINE_UUID=""
export SMALL_SCALE_BASELINE_PREFIX=""
export LARGE_SCALE_BASELINE_PREFIX=""
export GSHEET_KEY_LOCATION=""
export EMAIL_ID_FOR_RESULTS_SHEET=""
export THROUGHPUT_TOLERANCE=5
export LATENCY_TOLERANCE=5
export SERVICE_TYPE=NodePort
export KEEPALIVE_REQUESTS="0 1 50"
export LARGE_SCALE_THRESHOLD=24
export LARGE_SCALE_ROUTES=500
export LARGE_SCALE_CLIENTS="1 20 80"
export LARGE_SCALE_CLIENTS_MIX="1 10 20"
export SMALL_SCALE_ROUTES=100
export SMALL_SCALE_CLIENTS="1 40 200"
export SMALL_SCALE_CLIENTS_MIX="1 20 80"
export METADATA_COLLECTION=true
