apiVersion: v1
kind: Namespace
metadata:
  name: http-scale-client
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: http-scale-client
  namespace: http-scale-client
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: hostnetwork
  namespace: http-scale-client
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: system:openshift:scc:hostnetwork
subjects:
- kind: ServiceAccount
  name: http-scale-client
  namespace: http-scale-client
