---
jobs:
{{ if or (contains "http" .TERMINATIONS) (contains "mix" .TERMINATIONS) }}
- name: http-scale-http
  jobIterations: 1
  qps: 20
  burst: 20
  namespacedIterations: false
  namespace: http-scale-http
  cleanup: true
  waitWhenFinished: true
  namespaceLabels:
    security.openshift.io/scc.podSecurityLabelSync: false
    pod-security.kubernetes.io/enforce: privileged
    pod-security.kubernetes.io/audit: privileged
    pod-security.kubernetes.io/warn: privileged
  objects:
    - objectTemplate: templates/nginx-deploy.yml
      replicas: {{ .NUMBER_OF_ROUTES }}
      inputVars:
        deploymentReplicas: {{ .DEPLOYMENT_REPLICAS }}

    - objectTemplate: templates/http-service.yml
      replicas: {{ .NUMBER_OF_ROUTES }}
      inputVars:
        serviceType: {{ .SERVICE_TYPE }}

    - objectTemplate: templates/http-route.yml
      replicas: {{ .NUMBER_OF_ROUTES }}
{{ end }}

{{ if or (contains "edge" .TERMINATIONS) (contains "mix" .TERMINATIONS) }}
- name: http-scale-edge
  jobIterations: 1
  qps: 20
  burst: 20
  namespacedIterations: false
  namespace: http-scale-edge
  cleanup: true
  waitWhenFinished: true
  namespaceLabels:
    security.openshift.io/scc.podSecurityLabelSync: false
    pod-security.kubernetes.io/enforce: privileged
    pod-security.kubernetes.io/audit: privileged
    pod-security.kubernetes.io/warn: privileged
  objects:
    - objectTemplate: templates/nginx-deploy.yml
      replicas: {{ .NUMBER_OF_ROUTES }}
      inputVars:
        deploymentReplicas: {{ .DEPLOYMENT_REPLICAS }}

    - objectTemplate: templates/http-service.yml
      replicas: {{ .NUMBER_OF_ROUTES }}
      inputVars:
        serviceType: {{ .SERVICE_TYPE }}

    - objectTemplate: templates/edge-route.yml
      replicas: {{ .NUMBER_OF_ROUTES }}
{{ end }}

{{ if or (contains "passthrough" .TERMINATIONS) (contains "mix" .TERMINATIONS) }}
- name: http-scale-passthrough
  jobIterations: 1
  qps: 20
  burst: 20
  namespacedIterations: false
  namespace: http-scale-passthrough
  cleanup: true
  waitWhenFinished: true
  namespaceLabels:
    security.openshift.io/scc.podSecurityLabelSync: false
    pod-security.kubernetes.io/enforce: privileged
    pod-security.kubernetes.io/audit: privileged
    pod-security.kubernetes.io/warn: privileged
  objects:
    - objectTemplate: templates/nginx-deploy.yml
      replicas: {{ .NUMBER_OF_ROUTES }}
      inputVars:
        deploymentReplicas: {{ .DEPLOYMENT_REPLICAS }}

    - objectTemplate: templates/https-service.yml
      replicas: {{ .NUMBER_OF_ROUTES }}
      inputVars:
        serviceType: {{ .SERVICE_TYPE }}

    - objectTemplate: templates/passthrough-route.yml
      replicas: {{ .NUMBER_OF_ROUTES }}
{{ end }}

{{ if or (contains "reencrypt" .TERMINATIONS) (contains "mix" .TERMINATIONS) }}
- name: http-scale-reencrypt
  jobIterations: 1
  qps: 20
  burst: 20
  namespacedIterations: false
  namespace: http-scale-reencrypt
  cleanup: true
  waitWhenFinished: true
  namespaceLabels:
    security.openshift.io/scc.podSecurityLabelSync: false
    pod-security.kubernetes.io/enforce: privileged
    pod-security.kubernetes.io/audit: privileged
    pod-security.kubernetes.io/warn: privileged
  objects:
    - objectTemplate: templates/nginx-deploy.yml
      replicas: {{ .NUMBER_OF_ROUTES }}
      inputVars:
        deploymentReplicas: {{ .DEPLOYMENT_REPLICAS }}

    - objectTemplate: templates/https-service.yml
      replicas: {{ .NUMBER_OF_ROUTES }}
      inputVars:
        serviceType: {{ .SERVICE_TYPE }}

    - objectTemplate: templates/reencrypt-route.yml
      replicas: {{ .NUMBER_OF_ROUTES }}
{{ end }}

- name: http-scale-client
  namespace: http-scale-client
  jobIterations: 1
  namespacedIterations: false
  cleanup: true
  waitWhenFinished: true
  namespaceLabels:
    security.openshift.io/scc.podSecurityLabelSync: false
    pod-security.kubernetes.io/enforce: privileged
    pod-security.kubernetes.io/audit: privileged
    pod-security.kubernetes.io/warn: privileged
  objects:
    - objectTemplate: templates/http-client-rolebinding.yml
      replicas: 1

    - objectTemplate: templates/http-client-sa.yml
      replicas: 1

    - objectTemplate: templates/http-scale-client.yml
      replicas: 1
      inputVars:
        ESServer: "{{ .ES_SERVER }}"
        ESIndex: {{ .ES_INDEX }}
        hostNetwork: {{ .HOST_NETWORK }}
        nodeSelector: "{{ .NODE_SELECTOR }}"
        numberOfRouters: "{{ .NUMBER_OF_ROUTERS }}"
        clusterID: "{{ .CLUSTER_ID }}"
        clusterName: "{{ .CLUSTER_NAME }}"
        openshiftVersion: "{{ .OPENSHIFT_VERSION }}"
        kubernetesVersion: "{{ .KUBERNETES_VERSION }}"
        clusterNetworkType: "{{ .CLUSTER_NETWORK_TYPE }}"
        platformStatus: '{{ .PLATFORM_STATUS }}'
