apiVersion: tuned.openshift.io/v1
kind: Tuned
metadata:
  name: openshift-ingress-performance
  namespace: openshift-cluster-node-tuning-operator
spec:
  profile:
  - data: |
      [main]
      summary=Ingress performance profile
      include=openshift
      [sysctl]
      net.ipv4.ip_local_port_range="1024 65535"
      net.ipv4.tcp_tw_reuse=1
    name: openshift-ingress-performance
  recommend:
  - match:
    - label: node-role.kubernetes.io/workload
    priority: 10
    profile: openshift-ingress-performance

