apiVersion: batch/v1
kind: Job
metadata:
  name: loadgenerator
  labels:
    environment: development
    team: loadgenerator
    tier: test
spec:
  backoffLimit: 0
  ttlSecondsAfterFinished: 3600
  template:
    metadata:
      labels:
        app: loadgenerator
        environment: development
        team: loadgenerator
        tier: test
      annotations:
        sidecar.istio.io/rewriteAppHTTPProbers: "true"
    spec:
      restartPolicy: Never
      containers:
        - name: loadgenerator
          image: quay.io/msheth/boa-loadgenerator:v0.3
          imagePullPolicy: Always
          env:
            - name: FRONTEND_ADDR
              value: frontend:80
            - name: USERS
              value: "20"
            - name: LOG_LEVEL
              value: error
            - name: ES_SERVER
              value: "${ES_SERVER}"
            - name: UUID
              value: "${UUID}"
          startupProbe:
            exec:
              command:
                - sh
                - -c
                - |
                  curl -sf "http://frontend:80"
            initialDelaySeconds: 5
            periodSeconds: 5
            failureThreshold: 120
          resources:
            limits:
              cpu: 250m
              memory: 2Gi
            requests:
              cpu: 100m
              memory: 512Mi
          securityContext:
            allowPrivilegeEscalation: false
            capabilities:
              drop:
                - all
            privileged: false
            readOnlyRootFilesystem: false
      securityContext:
        fsGroup: 1000
        runAsGroup: 1000
        runAsNonRoot: true
        runAsUser: 1000
      serviceAccountName: default
      terminationGracePeriodSeconds: 5

